### ISSUE TITLE
Create CODE-OF-CONDUCT.md file

### ISSUE THREAD

**Issue by Sitanshu-AI** [Learn-Write-Repeat/DevMerch#3]
Create code of conduct file to define community standards

**Comment by bhavik-m** [comment]
i would like to create code of conduct file can you assign it to me ?

**Comment by Sitanshu-AI** [comment]
well i guess the person who creates issue will get assigned.

**Comment by arpit-dwivedi** [comment]
@Sitanshu-AI 
Go ahead with it!!

**Comment by swathi-469** [comment]
If the issue is open I would like to work on it. Please assign this to me

**Comment by foreverabhi2002** [comment]
@arpit-dwivedi Please assign this issue to someone else because @Sitanshu-AI is taking a lot time

**Comment by swathi-469** [comment]
Thanks a lot for assigning me

**Comment by swathi-469** [comment]
I have made my pull request please look over it

**Comment by foreverabhi2002** [comment]
@swathi-469 your pull request has been merged. Good Luck!
