### ISSUE TITLE
Frontend landing page

### ISSUE THREAD

**Issue by foreverabhi2002** [Learn-Write-Repeat/DevMerch#5]
Build a basic Frontend landing page similar to the ui design below
Should contain the following :-

- Basic NavBar with Nav Elements #9 
- A sliding banner for promotions/ merchandise related stuffs #10 
- Lists merchandise in a grid format #11 
- Basic Footer #12 

![DevMerch](https://user-images.githubusercontent.com/57245064/126357258-7befb03d-eb3e-4ae7-b224-5c0ab1cb9c02.png)

**This issue is not for resolving, for solving the above mentioned issues go to the link mentioned above next to these corresponding issues.**

**Comment by vanishasamriddhi** [comment]
I want to work on this. 
I've previously also worked on similar website, you may check that on my [LifeStyleStore](https://github.com/vanishasamriddhi/LifeStyleStore) repository

**Comment by foreverabhi2002** [comment]
@vanishasamriddhi Check the issue #9  #10  #11  #12 .
