### ISSUE TITLE
Sign up and login page

### ISSUE THREAD

**Issue by simranquirky** [Learn-Write-Repeat/DevMerch#6]
Create page for sign up/sign in

**Comment by simranquirky** [comment]
Can I move forward with page creation?

**Comment by foreverabhi2002** [comment]
@simranquirky can you come up with a basic and clean ui for the page?

**Comment by simranquirky** [comment]
> @simranquirky can you come up with a basic and clean ui for the page?

Yes , sure

**Comment by foreverabhi2002** [comment]
Go ahead, @simranquirky you have been assigned
