### ISSUE TITLE
Create Basic NavBar with Nav Elements

### ISSUE THREAD

**Issue by foreverabhi2002** [Learn-Write-Repeat/DevMerch#9]
Build a basic Navigation Bar with Navigation Elements similar to the ui design shown below.
https://user-images.githubusercontent.com/57245064/126357258-7befb03d-eb3e-4ae7-b224-5c0ab1cb9c02.png
Must contain the following elements

- Logo
- Search bar
- Contact
- About
- Cart
- Sign In and Log In
This issue is only for Navigation Bar only.
*Important Note - Try making the this responsive for the mobile as well*

**Comment by vanishasamriddhi** [comment]
I want to resolve this issue.

**Comment by foreverabhi2002** [comment]
@vanishasamriddhi  you have been assigned for this issue.
